if(document.querySelector(".comment-barrage")){let c=function(){if(commentBarrageConfig.dom){var e=JSON.stringify({event:"COMMENT_GET",accessToken:commentBarrageConfig.accessToken,url:commentBarrageConfig.pageUrl}),t=new XMLHttpRequest;t.withCredentials=!0,t.addEventListener("readystatechange",function(){this.readyState===4&&this.responseText&&(commentBarrageConfig.barrageList=i(JSON.parse(this.responseText).data),commentBarrageConfig.dom.innerHTML="")}),t.open("POST",commentBarrageConfig.twikooUrl),t.setRequestHeader("Content-Type","application/json"),t.send(e),clearInterval(commentInterval),commentInterval=null,commentInterval=setInterval(()=>{commentBarrageConfig.barrageList.length&&!hoverOnCommentBarrage&&(o(commentBarrageConfig.barrageList[commentBarrageConfig.barrageIndex]),commentBarrageConfig.barrageIndex+=1,commentBarrageConfig.barrageIndex%=commentBarrageConfig.barrageList.length),commentBarrageConfig.barrageTimer.length>(commentBarrageConfig.barrageList.length>commentBarrageConfig.maxBarrage?commentBarrageConfig.maxBarrage:commentBarrageConfig.barrageList.length)&&!hoverOnCommentBarrage&&d(commentBarrageConfig.barrageTimer.shift())},commentBarrageConfig.barrageTime)}},i=function(e){e.sort((a,s)=>a.created-s.created);let t=[];return e.forEach(a=>{t.push(...l(a))}),t},l=function(e){if(e.replies){let t=[e];return e.replies.forEach(a=>{t.push(...l(a))}),t}else return[]},o=function(e){let t=document.createElement("div");t.className="comment-barrage-item",t.innerHTML=`
          <div class="barrageHead">
            <a class="barrageTitle ${e.mailMd5===commentBarrageConfig.mailMd5?"barrageBloggerTitle":""}" href="javascript:anzhiyu.scrollTo('#post-comment')"">
              ${e.mailMd5===commentBarrageConfig.mailMd5?"\u535A\u4E3B":"\u70ED\u8BC4"}
            </a>
            <div class="barrageNick">${e.nick}</div>
            <img class="nolazyload barrageAvatar" src="https://cravatar.cn/avatar/${e.mailMd5}"/>
            <a class="comment-barrage-close" href="javascript:anzhiyu.switchCommentBarrage()"><i class="anzhiyufont anzhiyu-icon-xmark"></i></a>
          </div>
          <anzhiyu class="barrageContent" onClick="window.location.hash = '${e.id}'">
            ${e.comment}
          </anzhiyu>
        `,t.querySelectorAll("anzhiyu pre").forEach(r=>{let n=document.createElement("span");n.innerText="\u3010\u4EE3\u7801\u3011",r.parentNode.replaceChild(n,r)}),t.querySelectorAll("anzhiyu img").forEach(r=>{if(!r.classList.contains("tk-owo-emotion")){r.style.display="none";let n=document.createElement("span");n.innerText="\u3010\u56FE\u7247\u3011",r.parentNode.replaceChild(n,r)}}),commentBarrageConfig.barrageTimer.push(t),commentBarrageConfig.dom.append(t)},d=function(e){e.className="comment-barrage-item out",setTimeout(()=>{commentBarrageConfig.dom&&commentBarrageConfig.dom.contains(e)&&commentBarrageConfig.dom.removeChild(e)},1e3)};var initCommentBarrage=c,commentLinkFilter=i,getCommentReplies=l,popCommentBarrage=o,removeCommentBarrage=d,commentBarrageConfig={maxBarrage:GLOBAL_CONFIG.commentBarrageConfig.maxBarrage,barrageTime:GLOBAL_CONFIG.commentBarrageConfig.barrageTime,twikooUrl:GLOBAL_CONFIG.twikooEnvId,accessToken:GLOBAL_CONFIG.commentBarrageConfig.accessToken,mailMd5:GLOBAL_CONFIG.commentBarrageConfig.mailMd5,pageUrl:window.location.pathname,barrageTimer:[],barrageList:[],barrageIndex:0,dom:document.querySelector(".comment-barrage")},commentInterval=null,hoverOnCommentBarrage=!1;document.querySelector(".comment-barrage").addEventListener("mouseenter",function(){hoverOnCommentBarrage=!0}),document.querySelector(".comment-barrage").addEventListener("mouseleave",function(){hoverOnCommentBarrage=!1});const m=e=>{const t=document.querySelector(".comment-barrage"),a=document.getElementById("post-comment");e.forEach(s=>{a&&t&&document.body.clientWidth>768&&(t.style.bottom=s.isIntersecting?`-${commentBarrageConfig.maxBarrage*200}px`:"0")})},h=new IntersectionObserver(m,{root:null,rootMargin:"0px",threshold:0}),u=document.getElementById("post-comment");u&&h.observe(u),c(),localStorage.getItem("commentBarrageSwitch")!=="false"?(document.querySelector(".comment-barrage").style.display="flex",document.querySelector(".menu-commentBarrage-text").textContent="\u5173\u95ED\u70ED\u8BC4"):(document.querySelector(".comment-barrage").style.display="none",document.querySelector(".menu-commentBarrage-text").textContent="\u663E\u793A\u70ED\u8BC4"),document.addEventListener("pjax:send",function(){clearInterval(commentInterval)})}
